# -*- coding: utf-8 -*-
"""Prak7_SPK_G211200090.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B5oQfcGM4yO3ljbStSdY0xFeDKQdZ8Mm
"""

!pip install scikit-fuzzy --upgrade

import pandas as pd
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import skfuzzy as fuzz
from google.colab import files
uploaded = files.upload()

base = pd.read_csv('/content/UCI_Credit_Card.csv')

base.head()

base.shape

base['BILL TOTAL'] = base['BILL_AMT1']  + base['BILL_AMT2'] + base['BILL_AMT3'] + base['BILL_AMT4'] + base['BILL_AMT5'] + base['BILL_AMT6']

base.head()

X = base.iloc[:,[1,25]].values
X

scaler = StandardScaler()
X = scaler.fit_transform(X)

X

X.shape

X.T.shape

r = fuzz.cmeans(data = X.T, c = 3, m = 2, error=0.005, maxiter=1000, init=None)
r

previsoes_porcentagem = r[1]

previsoes_porcentagem.shape

previsoes_porcentagem

previsoes_porcentagem [0] [0]

previsoes_porcentagem [1] [0]

previsoes_porcentagem [2] [0]

previsoes_porcentagem [0] [0] + previsoes_porcentagem [1] [0] + previsoes_porcentagem [2] [0]

previsoes = previsoes_porcentagem.argmax(axis=0)
previsoes

previsoes[5000]

plt.scatter(X[previsoes == 0,0], X[previsoes == 0,1], s = 100, c = 'red', label = 'Cluster 1')
plt.scatter(X[previsoes == 1,0], X[previsoes == 1,1], s = 100, c = 'green', label = 'Cluster 2')
plt.scatter(X[previsoes == 2,0], X[previsoes == 2,1], s = 100, c = 'orange', label = 'Cluster 3')
plt.xlabel('Limite')
plt.ylabel('Gastos')
plt.legend();

